version: '3.1'

services:
  db:
    image: postgres
    container_name: db
    restart: always
    ports:
      - "5433:5433"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: digimon